/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTutorFeedbackRouteImport } from './routes/api/tutor-feedback'
import { Route as ApiMarkSchemeRouteImport } from './routes/api/mark-scheme'
import { Route as ApiGenerateProblemRouteImport } from './routes/api/generate-problem'
import { Route as ApiExtractProblemsRouteImport } from './routes/api/extract-problems'

const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTutorFeedbackRoute = ApiTutorFeedbackRouteImport.update({
  id: '/api/tutor-feedback',
  path: '/api/tutor-feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarkSchemeRoute = ApiMarkSchemeRouteImport.update({
  id: '/api/mark-scheme',
  path: '/api/mark-scheme',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateProblemRoute = ApiGenerateProblemRouteImport.update({
  id: '/api/generate-problem',
  path: '/api/generate-problem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractProblemsRoute = ApiExtractProblemsRouteImport.update({
  id: '/api/extract-problems',
  path: '/api/extract-problems',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/replay': typeof ReplayRoute
  '/tutor': typeof TutorRoute
  '/api/extract-problems': typeof ApiExtractProblemsRoute
  '/api/generate-problem': typeof ApiGenerateProblemRoute
  '/api/mark-scheme': typeof ApiMarkSchemeRoute
  '/api/tutor-feedback': typeof ApiTutorFeedbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/replay': typeof ReplayRoute
  '/tutor': typeof TutorRoute
  '/api/extract-problems': typeof ApiExtractProblemsRoute
  '/api/generate-problem': typeof ApiGenerateProblemRoute
  '/api/mark-scheme': typeof ApiMarkSchemeRoute
  '/api/tutor-feedback': typeof ApiTutorFeedbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/replay': typeof ReplayRoute
  '/tutor': typeof TutorRoute
  '/api/extract-problems': typeof ApiExtractProblemsRoute
  '/api/generate-problem': typeof ApiGenerateProblemRoute
  '/api/mark-scheme': typeof ApiMarkSchemeRoute
  '/api/tutor-feedback': typeof ApiTutorFeedbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/progress'
    | '/replay'
    | '/tutor'
    | '/api/extract-problems'
    | '/api/generate-problem'
    | '/api/mark-scheme'
    | '/api/tutor-feedback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/progress'
    | '/replay'
    | '/tutor'
    | '/api/extract-problems'
    | '/api/generate-problem'
    | '/api/mark-scheme'
    | '/api/tutor-feedback'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/progress'
    | '/replay'
    | '/tutor'
    | '/api/extract-problems'
    | '/api/generate-problem'
    | '/api/mark-scheme'
    | '/api/tutor-feedback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  ProgressRoute: typeof ProgressRoute
  ReplayRoute: typeof ReplayRoute
  TutorRoute: typeof TutorRoute
  ApiExtractProblemsRoute: typeof ApiExtractProblemsRoute
  ApiGenerateProblemRoute: typeof ApiGenerateProblemRoute
  ApiMarkSchemeRoute: typeof ApiMarkSchemeRoute
  ApiTutorFeedbackRoute: typeof ApiTutorFeedbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tutor-feedback': {
      id: '/api/tutor-feedback'
      path: '/api/tutor-feedback'
      fullPath: '/api/tutor-feedback'
      preLoaderRoute: typeof ApiTutorFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mark-scheme': {
      id: '/api/mark-scheme'
      path: '/api/mark-scheme'
      fullPath: '/api/mark-scheme'
      preLoaderRoute: typeof ApiMarkSchemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-problem': {
      id: '/api/generate-problem'
      path: '/api/generate-problem'
      fullPath: '/api/generate-problem'
      preLoaderRoute: typeof ApiGenerateProblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract-problems': {
      id: '/api/extract-problems'
      path: '/api/extract-problems'
      fullPath: '/api/extract-problems'
      preLoaderRoute: typeof ApiExtractProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  ProgressRoute: ProgressRoute,
  ReplayRoute: ReplayRoute,
  TutorRoute: TutorRoute,
  ApiExtractProblemsRoute: ApiExtractProblemsRoute,
  ApiGenerateProblemRoute: ApiGenerateProblemRoute,
  ApiMarkSchemeRoute: ApiMarkSchemeRoute,
  ApiTutorFeedbackRoute: ApiTutorFeedbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
